[FIX] openupgrade_framework: Allow missing path_info
For avoiding this error when using `load_data` openupgradelib method:

```
    ...
    File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5094, in _load_records
    data['record']._load_records_write(data['values'])
    File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 2171, in _load_records_write
    super(View, self)._load_records_write(values)
    File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5025, in _load_records_write
    self.write(values)
    ...
    File "/opt/odoo/auto/addons/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py", line 97, in _inverse_arch
    if path_info[0] == "openupgrade_scripts":
TypeError: 'NoneType' object is not subscriptable
```