[OU-FIX] hr_holidays: Crash if not active employees
As first, employee_ids are being filtered by active, but the if was
not changed in #5398

```
  File ".../openupgrade_scripts/scripts/hr_holidays/18.0.1.6/pre-migration.py", line 206, in migrate
    split_employee_leaves(env)
  File ".../openupgrade_scripts/scripts/hr_holidays/18.0.1.6/pre-migration.py", line 162, in split_employee_leaves
    SET employee_id = {employees[0].id}
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 7082, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range
```