[FIX] graph: Fix AttributeError
Fixes the following error:

```
Traceback (most recent call last):
  ...
  File "openupgrade/openerp/modules/graph.py", line 93, in add_modules
    forced_deps = tools.safe_eval.safe_eval(forced_deps)
AttributeError: 'function' object has no attribute 'safe_eval'
```

Since `eval` is actually the `safe_eval` function we can safely use it.