Model openupgrade.record inherited from itself
This was the error message, for those who may google it:

TypeError: The model "openupgrade.record" specifies an unexisting parent class "openupgrade.record"
You may need to add a dependency on the parent class' module.